# database/schemas.toml
# Schema definitions for food data tables

[food_consumption.commodity]
type = "str"
required = true
description = "Food item type (e.g., Almonds, Eggs)"

[food_consumption.age_group]
type = "str"
required = true
description = "Population age group (e.g., Adults, Children)"

[food_consumption.mean_consumption_chronic]
type = "float"
required = false
min = 0
description = "Average long-term consumption value"

[food_consumption.mean_consumption_acute]
type = "float"
required = false
min = 0
description = "Average short-term consumption value"

[food_consumption.percentile_97_chronic]
type = "float"
required = false
min = 0
description = "97th percentile of long-term consumption"

[food_consumption.percentile_97_acute]
type = "float"
required = false
min = 0
description = "97th percentile of short-term consumption"

[food_consumption.notes]
type = "str"
required = false
description = "Additional information about the food item"

# Example of another table schema that could be added
[trade_volumes.commodity]
type = "str"
required = true
description = "Food item being traded"

[trade_volumes.year]
type = "int"
required = true
min = 2000
description = "Year of trade data"

[trade_volumes.quarter]
type = "int"
required = true
min = 1
max = 4
description = "Quarter (1-4) of the year"

[trade_volumes.import_volume]
type = "float"
required = false
min = 0
description = "Volume of imports in tons"

[trade_volumes.export_volume]
type = "float"
required = false
min = 0
description = "Volume of exports in tons"

[trade_volumes.country_origin]
type = "str"
required = false
description = "Primary country of origin for imports"